steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'dockerfiles/trainer_gcs.dockerfile', '-t', 'gcr.io/dtumlops/trainer', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dtumlops/trainer']
timeout: 14400s