steps:
  - name: python
    entrypoint: bash
    args: ['-c', 'cp -r gs://birds_mlops/ data/']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'dockerfiles/trainer.dockerfile', '-t', 'gcr.io/dtumlops/testing', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dtumlops/trainer:latest']
timeout: 3600s