steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      gsutil -m cp -r 'gs://birds_mlops/data/ '/workspace'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'dockerfiles/trainer.dockerfile', '-t', 'gcr.io/dtumlops/testing', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dtumlops/trainer:latest']
timeout: 14400s