steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-f', 'trainer_cloud.dockerfile', '-t',  'gcr.io/dtumlops/trainer:latest', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/dtumlops/trainer:latest']
timeout: 3600s