steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'dockerfiles/trainer_gcs.dockerfile', '-t', 'gcr.io/igneous-visitor-410709/trainer', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/igneous-visitor-410709/trainer']
timeout: 14400s