site_name: mlops-face-shapes-project
site_author: Jonas s Roslev Gjerris Line Selma Petersen Christian Bakos Leirvåg
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
